import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

import '../../../widgets/animations/three_d_tilt_wrapper.dart';
import '../../../widgets/common/glass_container.dart';
import '../../../services/gamification_service.dart';
import '../../../services/groq_service.dart';

class WeeklyReportScreen extends StatefulWidget {
  const WeeklyReportScreen({super.key});

  @override
  State<WeeklyReportScreen> createState() => _WeeklyReportScreenState();
}

class _WeeklyReportScreenState extends State<WeeklyReportScreen> {
  final GamificationService _gamification = GamificationService();
  final GroqService _groq = GroqService();
  String _reportMarkdown = "";
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _generateReport();
  }

  Future<void> _generateReport() async {
    final user = FirebaseAuth.instance.currentUser;
    String userName = user?.displayName?.split(" ").first ?? "Explorer";
    
    // We pass the last 10 tasks to the AI to evaluate recent performance
    final recentTasks = _gamification.data.completedTasks.length > 10 
        ? _gamification.data.completedTasks.sublist(_gamification.data.completedTasks.length - 10)
        : _gamification.data.completedTasks;

    final report = await _groq.generateWeeklyReport(
      userName,
      _gamification.data.level,
      _gamification.data.xp,
      recentTasks,
      _gamification.data.careerGoal,
    );

    if (mounted) {
      setState(() {
        _reportMarkdown = report;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.white),
        title: Text(
          "AI Twin Report",
          style: GoogleFonts.poppins(
            color: Colors.white,
            fontWeight: FontWeight.bold,
            fontSize: 20,
          ),
        ),
        centerTitle: true,
      ),
      body: Stack(
        children: [
          // Background Glows
          Positioned(
            top: 40,
            left: -100,
            child: Container(
              width: 300,
              height: 300,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                boxShadow: [
                  BoxShadow(
                    color: Colors.blueAccent.withValues(alpha: 0.08),
                    blurRadius: 100,
                  ),
                ],
              ),
            ),
          ),
          
          _isLoading 
            ? _buildLoading()
            : _buildReport(context),
        ],
      ),
    );
  }

  Widget _buildLoading() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const CircularProgressIndicator(color: Colors.blueAccent),
          const SizedBox(height: 24),
          Text(
            "Your AI Twin is analyzing your progress...",
            style: GoogleFonts.poppins(
              color: Colors.white70,
              fontSize: 16,
            ),
          ).animate().fade().slideY(),
        ],
      ),
    );
  }

  Widget _buildReport(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ThreeDTiltWrapper(
            child: GlassContainer(
              width: double.infinity,
              padding: const EdgeInsets.all(24),
              borderRadius: BorderRadius.circular(28),
              child: Column(
                children: [
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Colors.blueAccent.withValues(alpha: 0.15),
                      shape: BoxShape.circle,
                    ),
                    child: const Icon(Icons.analytics_rounded, color: Colors.blueAccent, size: 40),
                  ),
                  const SizedBox(height: 16),
                  Text(
                    "Performance Review",
                    style: GoogleFonts.poppins(
                      color: Colors.white,
                      fontSize: 22,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    "Generated by your AI Career Twin",
                    style: GoogleFonts.poppins(
                      color: Colors.white70,
                      fontSize: 14,
                    ),
                  ),
                ],
              ),
            ),
          ).animate().fade(duration: 500.ms).slideY(begin: 0.1),

          const SizedBox(height: 32),

          GlassContainer(
            padding: const EdgeInsets.all(24),
            borderRadius: BorderRadius.circular(24),
            child: MarkdownBody(
              data: _reportMarkdown,
              styleSheet: MarkdownStyleSheet(
                h1: GoogleFonts.poppins(color: Colors.white, fontSize: 22, fontWeight: FontWeight.bold),
                h2: GoogleFonts.poppins(color: Colors.blueAccent, fontSize: 18, fontWeight: FontWeight.bold),
                h3: GoogleFonts.poppins(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600),
                p: GoogleFonts.poppins(color: Colors.white.withValues(alpha: 0.9), fontSize: 14, height: 1.6),
                listBullet: GoogleFonts.poppins(color: Colors.blueAccent, fontSize: 14),
                strong: GoogleFonts.poppins(color: Colors.white, fontWeight: FontWeight.bold),
              ),
            ),
          ).animate().fade(delay: 200.ms).slideY(),
          
          const SizedBox(height: 40),
        ],
      ),
    );
  }
}
