// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCke74v4df5nL8nkDN2tJBAF7zv6CaiLg',
    appId: '1:312513051794:web:6833d3a49c492a2b507a4b',
    messagingSenderId: '312513051794',
    projectId: 'careerpilot-a1c5d',
    authDomain: 'careerpilot-a1c5d.firebaseapp.com',
    storageBucket: 'careerpilot-a1c5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumElagjtqRzJ-o6J5IY11abTFodVZ8U4',
    appId: '1:312513051794:android:0816cb8d463a0b38507a4b',
    messagingSenderId: '312513051794',
    projectId: 'careerpilot-a1c5d',
    storageBucket: 'careerpilot-a1c5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLspQPVbyulXbGdySbyHNs4lCY7OEY3FI',
    appId: '1:312513051794:ios:9023172db18f0614507a4b',
    messagingSenderId: '312513051794',
    projectId: 'careerpilot-a1c5d',
    storageBucket: 'careerpilot-a1c5d.firebasestorage.app',
    iosClientId: '312513051794-pmp91i8qp2j75ljrvrb16jlv1p7m87dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerpilotAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLspQPVbyulXbGdySbyHNs4lCY7OEY3FI',
    appId: '1:312513051794:ios:9023172db18f0614507a4b',
    messagingSenderId: '312513051794',
    projectId: 'careerpilot-a1c5d',
    storageBucket: 'careerpilot-a1c5d.firebasestorage.app',
    iosClientId: '312513051794-pmp91i8qp2j75ljrvrb16jlv1p7m87dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerpilotAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCke74v4df5nL8nkDN2tJBAF7zv6CaiLg',
    appId: '1:312513051794:web:82dbd1cb7cff0e22507a4b',
    messagingSenderId: '312513051794',
    projectId: 'careerpilot-a1c5d',
    authDomain: 'careerpilot-a1c5d.firebaseapp.com',
    storageBucket: 'careerpilot-a1c5d.firebasestorage.app',
  );

}